# **Project 3 - Sales Analysis - ETL**

## Objectives

- Extract data from provided CSV file
- Clean it 
- Apply feature engineering if necessary 
- Remove any unnecessary columns
- Rename columns if necessary
- Save to a new CSV file


## Inputs

CSV files provided:

Sales_InvoiceData.csv


Note: original file stored in Data/OriginalFiles


## Outputs

CSV file created from ETL etc stored in Data/CleanedDataSets:

Sales_InvoiceData_Cleaned.csv



## Additional Comments

Developed an experimental ETL library which is in this project (modETL_library.py) 
Has lots of cool features so will be interesting to see how it works "in the field"

Used AI tool used to help with the ETL process:
- GitHub 
- Copilot 

See Documents/What_AI_Used_For.md for more details.

## Initalise Working Environment

In [22]:
#import libraries
import os
import numpy as np
import pandas as pd

#below solution provided by chatGPT 
import sys
from pathlib import Path

project_root = Path.cwd().parent

if str(project_root / "assets" / "python_files") not in sys.path:
    sys.path.insert(0, str(project_root / "assets" / "python_files"))
    
import modGlobal
import modETL_Library as modETL
#end solution provided by chatGPT

# Section 1 - Initalisation

## Intitialise All Variables To Be Used In Global Stack

In [23]:
#DataFrame vars for ETL
dfSales_DataSet = None
dfSales_DataSet_Work = None
dfTemp = None
dfCleaned = None

#missing values check vars
intLessThanZero = 0

#stores current directory
strCurrentDir = ""

#other vars
dictDataFrames = dict()
lstColumns = list()
intNum = 0

## Set Current Directory To Base Project Directory

In [24]:
#get project directory - default is jupyter notebook sub folder as that is where this file is located!
#so move back one to the project root path
# Source - https://stackoverflow.com/a/17726833
# Posted by chimpsarehungry
# Retrieved 2026-07-05, License - CC BY-SA 3.0

#get current folder
strCurrentDir = os.getcwd()

#is the last part of the path the project directory?
if not strCurrentDir.endswith(modGlobal.CNST_STR_PROJECT_DIR):
   #get current working directory and move back one to the project root path
   strCurrentDir =  os.path.normpath(os.getcwd() + os.sep + os.pardir)
   os.chdir(os.path.dirname(strCurrentDir))
   #change directory
   os.chdir(strCurrentDir)

#confirm current directory is project directory
print(f"Current Directory: \n {os.getcwd()}")

Current Directory:
 /Users/rogerwilliams/Projects/Python/CourseProjects/Project3-SalesAnalysis

## Create Project Folder Structure

In [25]:
#create project folder structure
modETL.funcCreateDirectories()

Folder Structure Created Successfully!

# Section 1 - Extraction

- Read csv file sales data-set.csv as other two do not require ETL (boo!)
- Move into working files directory
- Read csv file into a pandas dataframe
- Get schema info -> column and row numbers
- Get first 5 records
- Get list of column datatypes
- Get detailed schema infomation

## Read csv File Into Variable For Processing

In [26]:
#read csv file into DataFrame
dfSales_DataSet = modETL.funcReadFileReturnDataFrame("Sales_InvoiceData.csv")
#save as working csv file
modETL.funcSaveDataFrameToWorkingFile(dfSales_DataSet)

#read file from working files folder
#ETL library returns a dictionary of all files in the folder with the attribute name
#set to the actual csv filename
dictDataFrames = modETL.funcReadWorkingFilesReturnDictionary()
dfSales_DataSet = dictDataFrames["Sales_InvoiceData_Working.csv"]

Folder Structure Created Successfully!
Read Sales_InvoiceData.csv Into DataFrame

Saved: Sales_InvoiceData To Working Folder
1 csv Files Read Into DataFrames

DataFrames Created:
Sales_InvoiceData_Working.csv

## Get Schema Info - Sales_Features_DataSet

In [27]:
modETL.funcGetStructure(dfSales_DataSet)
dfSales_DataSet.head()

DataFrame Structure:
===================
<class 'pandas.DataFrame'>
RangeIndex: 189151 entries, 0 to 189150
Data columns (total 15 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Unnamed: 0           189151 non-null  int64
 1   INV_InvoiceID        189151 non-null  str
 2   INV_InvoiceDate      189151 non-null  str
 3   INV_SalesOrderID     189151 non-null  str
 4   INV_SOLineNbr        189151 non-null  int64
 5   INV_ItemID           189151 non-null  str
 6   IMA_ItemName         189151 non-null  str
 7   INV_ProdFam          188744 non-null  str
 8   INV_InvoiceQty       189151 non-null  float64
 9   INV_InvoiceAmt       189151 non-null  float64
 10  INV_CustomerID       189151 non-null  str
 11  CUS_BillName         189151 non-null  str
 12  INV_TerritoryCodes   188905 non-null  str
 13  CUS_BillContactName  107648 non-null  str
 14  CUS_ShipMethod       189151 non-null  str
dtypes: float64(2), int64(2), str(11)
memory usage: 50.0 MB
None


Summary of DataFrame Structure:
===============================
Numeric Columns:

          Unnamed: 0  INV_SOLineNbr  INV_InvoiceQty  INV_InvoiceAmt
count  189151.000000  189151.000000   189151.000000   189151.000000
mean    94575.000000       3.500283       21.540247      296.874155
std     54603.334721       4.690949      129.116010     1591.709197
min         0.000000       1.000000        1.000000    -1723.440000
25%     47287.500000       1.000000        1.000000       12.500000
50%     94575.000000       2.000000        3.000000       47.320000
75%    141862.500000       4.000000       10.000000      161.210000
max    189150.000000     104.000000    10000.000000   124635.000000


String Columns:

       INV_InvoiceID INV_InvoiceDate INV_SalesOrderID INV_ItemID  \
count         189151          189151           189151     189151
unique         78001            1691            66793       7558
top           271275      28/04/2011         Misc Inv   CARRIAGE
freq              61             515              407      14752

              IMA_ItemName   INV_ProdFam INV_CustomerID      CUS_BillName  \
count               189151        188744         189151            189151
unique                5862           130           1928              1597
top     UK Carrier Service  Fire Product           S654  Rexel UK Limited
freq                 15674         57593           7145              8034

       INV_TerritoryCodes CUS_BillContactName CUS_ShipMethod
count              188905              107648         189151
unique                 34                 777             12
top           South Coast      Andrew Johnson     UK Carrier
freq                21566                4824         129502


No DateTime   Columns Found!

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
0,0,180851,01/03/2011,140079,3,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
1,1,180851,01/03/2011,140079,4,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
2,2,180851,01/03/2011,140079,2,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
3,3,180834,01/03/2011,141347,1,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
4,4,180834,01/03/2011,141347,2,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day

## Observations - Sales_DataSet
189,151 rows
15 columns

Columns:

Unnamed,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod

Assuming Unnamed is an index column and can be dropped if necessary  

We can also see the data types:  

Unnamed : int64. 
INV_InvoiceID : int64  
INV_InvoiceDate : str  
INV_SalesOrderID : str  
INV_SOLineNbr : int64  
INV_ItemID : str   
IMA_ItemName : str   
INV_ProdFam : str   
INV_InvoiceQty : float64     
INV_InvoiceAmt : float64   
INV_CustomerID : str    
CUS_BillName : str    
INV_TerritoryCodes : str  
CUS_BillContactName : str  
CUS_ShipMethod : str  

In the Summary of Dataframe Structure for numerical values we see this:

DataFrame Structure:  
===================  
<class 'pandas.DataFrame'>  
RangeIndex: 189151 entries, 0 to 189150  
Data columns (total 15 columns):  

|     |Column               |Non-Null Count |  Dtype  |    
|-----|---------------------|---------------|---------|  
| 0   |Unnamed: 0           |189151 non-null|  int64  |  
| 1   |INV_InvoiceID        |189151 non-null|  str    |  
| 2   |INV_InvoiceDate      |189151 non-null|  str    |  
| 3   |INV_SalesOrderID     |189151 non-null|  str    |  
| 4   |INV_SOLineNbr        |189151 non-null|  int64  |  
| 5   |INV_ItemID           |189151 non-null|  str    |         
| 6   |IMA_ItemName         |189151 non-null|  str    |
| 7   |INV_ProdFam          |188744 non-null|  str    |
| 8   |INV_InvoiceQty       |189151 non-null|  float64|  
| 9   |INV_InvoiceAmt       |189151 non-null|  float64|  
| 10  |INV_CustomerID       |189151 non-null|  str    |
| 11  |CUS_BillName         |189151 non-null|  str    |
| 12  |INV_TerritoryCodes   |188905 non-null|  str    |
| 13  |CUS_BillContactName  |107648 non-null|  str    |
| 14  |CUS_ShipMethod       |189151 non-null|  str    |

dtypes: float64(2), int64(2), str(12)  
memory usage: 50.0 MB. 
None

Looks like there are some null values in the INV_ProdFam, INV_TerritoryCodes and CUS_BillContactName  

Summary of DataFrame Structure:
===============================
Numeric Columns:

|       |    Unnamed: 0 |INV_SOLineNbr   |INV_InvoiceQty|INV_InvoiceAmt| 
|-------|---------------|----------------|--------------|--------------|  
|count  |189151.000000  |189151.000000   |189151.000000 |189151.000000 |
|mean   | 94575.000000  |     3.500283   |    21.540247 |   296.874155 |
|std    | 54603.334721  |     4.690949   |   129.116010 |  1591.709197 |
|min    |     0.000000  |     1.000000   |     1.000000 | -1723.440000 |
|25%    | 47287.500000  |     1.000000   |     1.000000 |.   12.500000 |
|50%    | 94575.000000  |     2.000000   |     3.000000 |    47.320000 |
|75%    |141862.500000  |     4.000000   |    10.000000 |   161.210000 |
|max    |189150.000000  |   104.000000   | 10000.000000 |124635.000000 |


String Columns:

|       |INV_InvoiceID  |   INV_InvoiceDate |INV_SalesOrderID |INV_ItemID|  
|-------|---------------|-------------------|-----------------|----------|
|count  |189151         |            189151 |          189151 |    189151|   
|unique | 78001         |              1691 |           66793 |      7558|   
|top    |271275         |28/4/2011 00:00:00 |        Misc Inv |  CARRIAGE|   
|freq   |    61.        |               515 |             407 |     14752|     
  
<br>

|       |       IMA_ItemName|   INV_ProdFam| INV_CustomerID|  
|-------|-------------------|--------------|---------------|
|count  |             189151|        188744|         189151|   
|unique |               5862|           130|           1928|   
|top    | UK Carrier Service|  Fire Product|           S654|   
|freq   |              15674|         57593|           7145|     

<br>    

|        |    CUS_BillName| INV_TerritoryCodes| CUS_BillContactName| CUS_ShipMethod|  
|--------|----------------|-------------------|--------------------|---------------|
|count   |          189151|             188905|              107648|         189151|  
|unique  |            1597|                 34|                 777|             12| 
|top     |Rexel UK Limited|        South Coast|      Andrew Johnson|     UK Carrier|  
|freq    |            8034|              21566|                4824|         129502|  
  






**What Does This Mean?**

- Count is how many values are in the columns
- Mean is the average value of the column
- Std is the standard deviation of the column 
  Standard deviation is how far from the average (mean) the values are. The closer to 0 the
  more consistent the values are i.e. not much deviation from the mean. The deviation range 
  can be referred to as the Sigma. The measurement is based on the Alpha this is a percentage
  of the mean used to determine variance. ypically this is set to 5%
- Min is the minimum value of the column
- 25% is the value at the 25th percentile of the column
- 50% is the value between the 25th and 75th percentiles of the column
- 75% is the value at the 75th percentile of the column

The middle 50% is also called the Interquartile Range (IQR) and its width can be set by changing the
alpha value which is normally 5%

**What?**

Percentile is a technical term for a 25% segment of the data. 
50% is the mean, 25% is below that and 75% is 25%above that, this crude picture illustrates this:

 1st Percentile      2nd Percentile        3rd Percentile
0      -      25%  25%      -     75%   75%      -     100%  

Note: 2nd percentile can also be called Central Tendency

- Max is the maximum value of the column

What we can see is some columns need to be populated more as null seem to be present, let us look further..

# Get Column Data Types

In [28]:
#get column data types
print (f"Data Types: \n{dfSales_DataSet.dtypes}")

Data Types:
Unnamed: 0               int64
INV_InvoiceID              str
INV_InvoiceDate            str
INV_SalesOrderID           str
INV_SOLineNbr            int64
INV_ItemID                 str
IMA_ItemName               str
INV_ProdFam                str
INV_InvoiceQty         float64
INV_InvoiceAmt         float64
INV_CustomerID             str
CUS_BillName               str
INV_TerritoryCodes         str
CUS_BillContactName        str
CUS_ShipMethod             str
dtype: object

## Observations - Sales_DataSet

- INV_InvoiceDate is a string - needs conversion to datetime

## Get Schema Statistics

Look for duplicates and missing values

In [29]:
#get column statistics
modETL.funcGetStatistics(dfSales_DataSet)

DataFrame Statistics:
=====================
          Unnamed: 0  INV_SOLineNbr  INV_InvoiceQty  INV_InvoiceAmt
count  189151.000000  189151.000000   189151.000000   189151.000000
mean    94575.000000       3.500283       21.540247      296.874155
std     54603.334721       4.690949      129.116010     1591.709197
min         0.000000       1.000000        1.000000    -1723.440000
25%     47287.500000       1.000000        1.000000       12.500000
50%     94575.000000       2.000000        3.000000       47.320000
75%    141862.500000       4.000000       10.000000      161.210000
max    189150.000000     104.000000    10000.000000   124635.000000


DataFrame Shape:
================
Rows: 189151, Columns: 15


Missing Values Per Column:
==========================
INV_ProdFam          - 407: Missing Values, 0.22% Percent Missing Values
INV_TerritoryCodes   - 246: Missing Values, 0.13% Percent Missing Values
CUS_BillContactName  - 81503: Missing Values, 43.09% Percent Missing Values


Duplicate Value Count Per Column:
=================================
INV_InvoiceID        Total Values: 189151  Duplicate Values: 111150, 58.76% Percent Duplicate Values
INV_InvoiceDate      Total Values: 189151  Duplicate Values: 187460, 99.11% Percent Duplicate Values
INV_SalesOrderID     Total Values: 189151  Duplicate Values: 122358, 64.69% Percent Duplicate Values
INV_SOLineNbr        Total Values: 189151  Duplicate Values: 189047, 99.95% Percent Duplicate Values
INV_ItemID           Total Values: 189151  Duplicate Values: 181593, 96.00% Percent Duplicate Values
IMA_ItemName         Total Values: 189151  Duplicate Values: 183289, 96.90% Percent Duplicate Values
INV_ProdFam          Total Values: 188744  Duplicate Values: 189020, 99.93% Percent Duplicate Values
INV_InvoiceQty       Total Values: 189151  Duplicate Values: 188559, 99.69% Percent Duplicate Values
INV_InvoiceAmt       Total Values: 189151  Duplicate Values: 157069, 83.04% Percent Duplicate Values
INV_CustomerID       Total Values: 189151  Duplicate Values: 187223, 98.98% Percent Duplicate Values
CUS_BillName         Total Values: 189151  Duplicate Values: 187554, 99.16% Percent Duplicate Values
INV_TerritoryCodes   Total Values: 188905  Duplicate Values: 189116, 99.98% Percent Duplicate Values
CUS_BillContactName  Total Values: 107648  Duplicate Values: 188373, 99.59% Percent Duplicate Values
CUS_ShipMethod       Total Values: 189151  Duplicate Values: 189139, 99.99% Percent Duplicate Values

## Observations - Sales_DataSet

Observations:
- Missing Values in INV_ProdFam, INV_TerritoryCodes and CUS_BillContactName
- High duplicates expected in shown columns as nature of data in them would create this situation

---

## Get Unique Values - Sales_DataSet

In [30]:
#show unique values count
modETL.funcGetUniqueValuesCount(dfSales_DataSet)

DataFrame Unique Values Per Column:
===================================
Unnamed: 0           - 189151: Unique Values Out Of 189151 Total Values
INV_InvoiceID        - 78001: Unique Values Out Of 189151 Total Values
INV_InvoiceDate      - 1691: Unique Values Out Of 189151 Total Values
INV_SalesOrderID     - 66793: Unique Values Out Of 189151 Total Values
INV_SOLineNbr        - 104: Unique Values Out Of 189151 Total Values
INV_ItemID           - 7558: Unique Values Out Of 189151 Total Values
IMA_ItemName         - 5862: Unique Values Out Of 189151 Total Values
INV_ProdFam          - 130: Unique Values Out Of 188744 Total Values
INV_InvoiceQty       - 592: Unique Values Out Of 189151 Total Values
INV_InvoiceAmt       - 32082: Unique Values Out Of 189151 Total Values
INV_CustomerID       - 1928: Unique Values Out Of 189151 Total Values
CUS_BillName         - 1597: Unique Values Out Of 189151 Total Values
INV_TerritoryCodes   - 34: Unique Values Out Of 188905 Total Values
CUS_BillContactName  - 777: Unique Values Out Of 107648 Total Values
CUS_ShipMethod       - 12: Unique Values Out Of 189151 Total Values

## Observations - Sales_DataSet

The columns where I would expect to see high unique values are:
- INV_InvoiceID
- INV_SalesOrderID
- INV_InvoiceAmt
- *INV_InvoiceDate

This is shown in the results

* INV_InvoiceDate is not showing high unique value because it is currently a string with 00:00:00 at the end
  confident when converted to datetime this will be resolved

## Get Categorical Value Distribution

In [31]:
#get categorical distribution  
modETL.funcGetCategoricalValueDistribution(dfSales_DataSet)

DataFrame Categorical Value Distribution:
=========================================
[INV_InvoiceID] Value Distribution:
INV_InvoiceID
271275    61
198715    51
214246    44
252525    40
226521    39
          ..
272068     1
272084     1
272075     1
272062     1
272092     1
Name: count, Length: 78001, dtype: int64


[INV_InvoiceDate] Value Distribution:
INV_InvoiceDate
28/04/2011    515
29/07/2011    492
30/11/2012    485
31/10/2011    449
31/07/2012    429
             ...
01/09/2016     26
27/05/2014      9
01/04/2014      4
01/02/2013      2
03/04/2012      1
Name: count, Length: 1691, dtype: int64


[INV_SalesOrderID] Value Distribution:
INV_SalesOrderID
Misc Inv    407
155671       92
168267       72
220144       64
165933       52
           ...
220878        1
220870        1
220409        1
220984        1
220980        1
Name: count, Length: 66793, dtype: int64


[INV_ItemID] Value Distribution:

INV_ItemID
CARRIAGE                     14752
L19EB                         4216
FPA-236                       2355
FPA-235                       2210
FPA-1009                      2096
                             ...
ODS20/NM3/IP/220V60HZ EXP        1
AR2X8/NM3/AD2 ORB                1
CHE2X8/NM3/AD2 ORB               1
ED8/NM3/AD2 ORB                  1
DST/ODETSCREW KIT                1
Name: count, Length: 7558, dtype: int64


[IMA_ItemName] Value Distribution:
IMA_ItemName
UK Carrier Service                                                                     15674
Legend  L19  For E/B 379 X 186 X 2mm Opal Polycarbonate                                 4541
S65 Optical Detector.  Apollo Series 65 Conventional Devices                            2564
S65 Detectors Base with Diode.  Apollo Series 65 Conventional Devices                   2417
8 Watt Economy NM3 Eden with White Base & Fresnel Diffuser.                             2321
                                                                                       ...
10 Amp 5 Zone Smoke Vent Control Panel                                                     1
New Style Odet 2x20W Tungsten Halogen NM3 IP65 for 220V 60HZ Supply (See Long Desc)        1
2x8W NM3 Chella Pris Diff With WH Trim Inc Addressable Unit Version 2                      1
8W NM3 Eden inc Addressable Interface V2                                                   1
Fixing Kit for Self Test Adapter Unit (Odet Version DST's)                                 1
Name: count, Length: 5862, dtype: int64


[INV_ProdFam] Value Distribution:
INV_ProdFam
Fire Product           57593
Accessories            21511
Global Component       16077
Luminaire Component    11476
Batteries               8702
                       ...
PLT                        1
Commissioning              1
LOWBAY                     1
ECOSTAR                    1
D-MET                      1
Name: count, Length: 130, dtype: int64


[INV_CustomerID] Value Distribution:
INV_CustomerID
S654     7145
S1361    4785
S1736    3899
75       3131
1028     3048
         ...
S638        1
S733        1
739         1
757         1
s2191       1
Name: count, Length: 1928, dtype: int64


[CUS_BillName] Value Distribution:
CUS_BillName
Rexel UK Limited                              8034
Lincs Electrical Wholesalers Limited          4824
TLC (SOUTHERN) Limited                        3953
ITAB UK Limited                               3131
Imci Services Ltd                             3048
                                              ...
Alliance Electrical Wholesalers Limited          1
AINAF International Inc.                         1
Electric Center (Edmundson)                      1
Jane Castle-Jenkins (Berwick Street Mills)       1
GRAYTRADE LTD                                    1
Name: count, Length: 1597, dtype: int64


[INV_TerritoryCodes] Value Distribution:
INV_TerritoryCodes
South Coast              21566
North West               17420
Non EU                   17282
East Midlands            12845
North East               12442
West Midlands (East)     11958
South East/London        10527
East Anglia               9617
South West                8249
North                     7738
West Midlands (West)      7185
House Account             7125
Central/E.Anglia          7067
Midlands and West         6250
Scotland                  5585
Midlands and East         4863
West Midlands             3798
South East                3454
North East/Yorkshire      3073
Midlands                  2813
EU                        2797
Midlands (South West)     1566
EU INV                    1541
London                     957
North West (South)         376
Northern Ireland           343
Scotland Depot             228
Services                    81
none                        65
EU - OTHER  EUROPE          49
Training                    20
UK Projects                 19
Ireland                      4
Southern Ireland             2
Name: count, dtype: int64


[CUS_BillContactName] Value Distribution:
CUS_BillContactName
Andrew Johnson               4824
Richard Mulligan             4296
Roger Meakin                 3953
Peter Luckin                 3131
do not change above email    3048
                             ...
Lawrence Fung                   1
Adrien POUPIN                   1
Roland Leblanc                  1
Mark Downes                     1
Ainaf Suppliers                 1
Name: count, Length: 777, dtype: int64


[CUS_ShipMethod] Value Distribution:
CUS_ShipMethod
UK Carrier                    129502
Export                         24505
Despatch Next Day              15352
Customer Collection            10470
Interlink                       4137
Amtrak                          2591
Express Despatch  Next Day      1416
Orbik Transport                 1097
Own Transport                     40
Despatch  3 Day                   21
Saturday Delivery                 18
DHL                                2
Name: count, dtype: int64

## Observations - Get Categorical Value Distribution

Some very interesting statistics here, a lot of the categorical columns such asINV_TerritoryCodes, show effectively the most common values which in itself is an interesting piece of analysis

# Section 2

- If missing values determine what to fill with (mean, mode or categorical something else)
- Transform data types if necessary

In [32]:
## Create Copy Of DataFrame
dfSales_DataSet_Work = dfSales_DataSet.copy()

## Strip Spaces From Date Column

In [33]:
#remove spaces from Date column (string datatype)
dfSales_DataSet_Work["INV_InvoiceDate"] = dfSales_DataSet_Work["INV_InvoiceDate"].str.strip()
          
#show first 50 rows to check    
dfSales_DataSet_Work.head(50)

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
0,0,180851,01/03/2011,140079,3,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
1,1,180851,01/03/2011,140079,4,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
2,2,180851,01/03/2011,140079,2,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
3,3,180834,01/03/2011,141347,1,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
4,4,180834,01/03/2011,141347,2,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
5,5,180860,01/03/2011,141420,1,gn8/m3/ex orb,Geneva 8W M3 Edge-Lit Exit. White Finish,Geneva,6.0,402.72,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
6,6,180860,01/03/2011,141420,2,l1620el-b,Legend Printed L16 One Side L20 Other Suitable...,Luminaire Component,4.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
7,7,180847,01/03/2011,141483,1,LV28C/BR ORB,INACTIVE Lavaine 28W 2D Mains Brass Style C,Lavaine,1.0,48.69,S1364,City Electrical Factors (Hinckley Group),North West,Richard Whitehurst,UK Carrier
8,8,180860,01/03/2011,141420,3,l19el-b,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,2.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
9,9,180832,01/03/2011,141642,3,TLC/3M TLC,8 Watt Economy M3 Eden with White Base & Clear...,Eden,19.0,228.95,S1736,TLC (SOUTHERN) Limited,South Coast,Roger Meakin,UK Carrier
10,10,180839,01/03/2011,141671,1,ar8/nm3 orb,8W NM3 Arc,Arc,16.0,316.96,S751,ABCO Electrical Distributors Limited,South West,Mike Merrit,UK Carrier
11,11,180827,01/03/2011,141672,1,LV16C/M3/BR ORB,Lavaine 16W 2D M3 HF Brass Style C,Lavaine,5.0,467.70,s1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
12,12,180829,01/03/2011,141676,2,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,25.0,220.00,S1551,Edmundson Electrical (400),North West,NaN,UK Carrier
13,13,180830,01/03/2011,141662,2,17-1115,Metalwork Recessing Bracket For 430mm Larino/C...,Accessories,1.0,4.30,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
14,14,180824,01/03/2011,141663,1,fpa-006,Surface Mount Call Point Red,Fire Product,1.0,5.67,S1140,Powerlec (ACCOUNT CLOSED) Distributors Limited,West Midlands (East),Dave Downes,Customer Collection
15,15,180835,01/03/2011,141664,2,fpa-236,S65 Optical Detector. Apollo Series 65 Conven...,Fire Product,7.0,70.00,S2191,LH Electrical Limited,East Midlands,Liam Hassell,UK Carrier
16,16,180862,01/03/2011,141684,4,L19EL-B,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,2.0,0.00,S1024,Premier Electrical Limited,North West,David Freshwater/Neil Glencross,Interlink
17,17,180849,01/03/2011,141689,1,FP-042,4 Zone 2-Wire Panel,Fire Product,1.0,135.00,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
18,18,180849,01/03/2011,141689,3,FPA-246,Apollo Smoke/Sounder Complete wtih Base 2-Wire...,Fire Product,5.0,107.85,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
19,19,180849,01/03/2011,141689,4,FPA-245,Alarmsense Optical Detector. Apollo Alarmsens...,Fire Product,6.0,61.32,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
20,20,180849,01/03/2011,141689,5,FPA-243,Alarmsense Detector Base. Apollo Alarmsense 2...,Fire Product,6.0,17.28,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
21,21,180852,01/03/2011,141692,1,PIC8/M3/E/BR ORB,INACTIVE 8W M3 S/Sided Pico Low Profile E/Box ...,Pico,1.0,42.00,S1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
22,22,180852,01/03/2011,141692,2,L19EB,Legend L19 For E/B 379 X 186 X 2mm Opal Poly...,Accessories,1.0,0.00,S1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
23,23,180831,01/03/2011,141687,1,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,2.0,17.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
24,24,180831,01/03/2011,141687,3,17-782/WHT,"Metalwork. Semi Recess Flange for Arc, Powder ...",Accessories,2.0,12.24,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
25,25,180831,01/03/2011,141687,4,27-102,Metalwork.Recessing Frame Fixing Bracket,Accessories,2.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
26,26,180830,01/03/2011,141662,1,kn16/m3 orb,16W 2D M3 Kandel White Opal Diff,Kandel,1.0,49.22,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
27,27,180830,01/03/2011,141662,3,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
28,28,180835,01/03/2011,141664,1,fpa-235,S65 Detectors Base with Diode. Apollo Series ...,Fire Product,7.0,12.53,S2191,LH Electrical Limited,East Midlands,Liam Hassell,UK Carrier
29,29,180839,01/03/2011,141671,2,ar8/m3 orb,Arc 8W HF M3,Arc,6.0,144.96,S751,ABCO Electrical Distributors Limited,South West,Mike Merrit,UK Carrier
30,30,180829,01/03/2011,141676,1,FPA-122,INACTIVE Smoke Detector Test Aerosol (250ml),Fire Product,5.0,32.20,S1551,Edmundson Electrical (400),North West,NaN,UK Carrier
31,31,180838,01/03/2011,141682,1,ODS20/NM3/TH ORB,New Style Odet 2x20W Tungsten Halogen NM3 Grey...,Odet,2.0,105.56,S654,Rexel UK Limited,West Midlands (East),NaN,UK Carrier
32,32,180831,01/03/2011,141687,2,ED8/M3/E ORB,8 Watt Economy M3 Eden with White Base & Fresn...,Eden,2.0,22.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
33,33,180831,01/03/2011,141687,5,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
34,34,180831,01/03/2011,141687,6,FPA-235,S65 Detectors Base with Diode. Apollo Series ...,Fire Product,1.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
35,35,180849,01/03/2011,141689,2,FPA-240,Alarmsense Heat Comb. Apollo Alarmsense 2-Wir...,Fire Product,1.0,21.57,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
36,36,180863,01/03/2011,141704,1,MZ28/M3 ORB,28W 2D Maintained Mezzina White Pr Diff,Mezzina,6.0,304.02,S1480,Edmundson Electrical (110),West Midlands (East),NaN,UK Carrier
37,37,180859,01/03/2011,141705,2,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,3.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
38,38,180858,01/03/2011,141703,1,FP-018,Use FP-313 Conventional Panel with 4 Zones fo...,Fire Product,1.0,137.93,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
39,39,180858,01/03/2011,141703,3,FPA-1010,Twin Flex & Multipoint,Fire Product,14.0,260.40,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
40,40,180858,01/03/2011,141703,4,FPA-1011,Twin Flex Call Point,Fire Product,4.0,40.80,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
41,41,180863,01/03/2011,141704,2,ML4003P3 ORB,M3 Low Profile Module 3x4Ah + DDP For 16W 2D-3...,ML-Range,10.0,198.10,S1480,Edmundson Electrical (110),West Midlands (East),NaN,UK Carrier
42,42,180859,01/03/2011,141705,1,SAV8/NM3/WH/A ORB,8W NM3 Savona Edge Lit E/Sign Head White Size A,Savona,5.0,309.65,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
43,43,180859,01/03/2011,141705,3,L16EL-A,Legend Printed L16 S/Sided Suitable For All Ed...,Accessories,1.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
44,44,180859,01/03/2011,141705,4,L20EL-A,Legend Printed L20 S/Sided Suitable For All Ed...,Accessories,1.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
45,45,180857,01/03/2011,141397,1,ods21/nm3/tm14 orb,New Style Odet 2x21W Tungsten NM3 Grey Inc 14 ...,Odet,4.0,282.04,S236,Rexel UK - AP Department (M3),East Midlands,NaN,UK Carrier
46,46,180856,01/03/2011,141699,1,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,6.0,54.00,S1521,Eyre & Elliston Limited,West Midlands (East),NaN,UK Carrier
47,47,180833,01/03/2011,141661,1,b165/315 orb,3x1.5Ah Nickel Cadmium In Line Battery with En...,Batteries,2.0,14.88,S1846,Herts Electrical Wholesale Limited,East Anglia,Stuart Beevor,UK Carrier
48,48,180825,01/03/2011,141665,1,16-618,Battery 3x1.5Ah Stick Sleeved & Tagged with Re...,Battery Component,1.0,5.06,s1212,ADI Gardiner Limited,North West,NaN,UK Carrier
49,49,180840,01/03/2011,141685,1,28-489,Self Adhesive European Directive Stickers (Sma...,Accessories,12.0,18.96,S816,GCG Electrical Wholesalers (Edmundson 584),West Midlands (West),Barry Guest,Customer Collection

## Observations - Sales_DataSet

No data corruptions

## Validate Numerical Values For Columns Used In Analysis

- see if INV_InvoiceQty has any values less than 1 
- see if INV_InvoiceAmt has any values less than 1

In [34]:
#get count of how many values in INV_InvoiceQty column are less than 1
intLessThanOne = (dfSales_DataSet_Work["INV_InvoiceQty"] < 1).sum()
#print result
print(f"Number of Values In INV_InvoiceQty Less Than 1: {intLessThanOne}")

#get count of how many values in INV_InvoiceAmt column are less than 1
intLessThanOne = (dfSales_DataSet_Work["INV_InvoiceAmt"] < 1).sum()
#print result
print(f"Number of Values In INV_InvoiceAmt Less Than 1: {intLessThanOne}")

Number of Values In INV_InvoiceQty Less Than 1: 0
Number of Values In INV_InvoiceAmt Less Than 1: 32766

---

## Observations - Sales_DataSet

With INV_InvoiceAmt having some values less than 1, is unusual, could be a credit note, due to the volume
will treat as such for the time being

## Data Transformations/Feature Engineering

Convert INV_InvoiceDate column to datetime format

In [35]:
#convert Date column to datetime format
dfSales_DataSet_Work["INV_InvoiceDate"] = pd.to_datetime(dfSales_DataSet["INV_InvoiceDate"], format="%d/%m/%Y")

#check results
dfSales_DataSet_Work.head(50)

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
0,0,180851,2011-03-01,140079,3,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
1,1,180851,2011-03-01,140079,4,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
2,2,180851,2011-03-01,140079,2,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
3,3,180834,2011-03-01,141347,1,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
4,4,180834,2011-03-01,141347,2,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
5,5,180860,2011-03-01,141420,1,gn8/m3/ex orb,Geneva 8W M3 Edge-Lit Exit. White Finish,Geneva,6.0,402.72,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
6,6,180860,2011-03-01,141420,2,l1620el-b,Legend Printed L16 One Side L20 Other Suitable...,Luminaire Component,4.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
7,7,180847,2011-03-01,141483,1,LV28C/BR ORB,INACTIVE Lavaine 28W 2D Mains Brass Style C,Lavaine,1.0,48.69,S1364,City Electrical Factors (Hinckley Group),North West,Richard Whitehurst,UK Carrier
8,8,180860,2011-03-01,141420,3,l19el-b,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,2.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
9,9,180832,2011-03-01,141642,3,TLC/3M TLC,8 Watt Economy M3 Eden with White Base & Clear...,Eden,19.0,228.95,S1736,TLC (SOUTHERN) Limited,South Coast,Roger Meakin,UK Carrier
10,10,180839,2011-03-01,141671,1,ar8/nm3 orb,8W NM3 Arc,Arc,16.0,316.96,S751,ABCO Electrical Distributors Limited,South West,Mike Merrit,UK Carrier
11,11,180827,2011-03-01,141672,1,LV16C/M3/BR ORB,Lavaine 16W 2D M3 HF Brass Style C,Lavaine,5.0,467.70,s1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
12,12,180829,2011-03-01,141676,2,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,25.0,220.00,S1551,Edmundson Electrical (400),North West,NaN,UK Carrier
13,13,180830,2011-03-01,141662,2,17-1115,Metalwork Recessing Bracket For 430mm Larino/C...,Accessories,1.0,4.30,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
14,14,180824,2011-03-01,141663,1,fpa-006,Surface Mount Call Point Red,Fire Product,1.0,5.67,S1140,Powerlec (ACCOUNT CLOSED) Distributors Limited,West Midlands (East),Dave Downes,Customer Collection
15,15,180835,2011-03-01,141664,2,fpa-236,S65 Optical Detector. Apollo Series 65 Conven...,Fire Product,7.0,70.00,S2191,LH Electrical Limited,East Midlands,Liam Hassell,UK Carrier
16,16,180862,2011-03-01,141684,4,L19EL-B,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,2.0,0.00,S1024,Premier Electrical Limited,North West,David Freshwater/Neil Glencross,Interlink
17,17,180849,2011-03-01,141689,1,FP-042,4 Zone 2-Wire Panel,Fire Product,1.0,135.00,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
18,18,180849,2011-03-01,141689,3,FPA-246,Apollo Smoke/Sounder Complete wtih Base 2-Wire...,Fire Product,5.0,107.85,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
19,19,180849,2011-03-01,141689,4,FPA-245,Alarmsense Optical Detector. Apollo Alarmsens...,Fire Product,6.0,61.32,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
20,20,180849,2011-03-01,141689,5,FPA-243,Alarmsense Detector Base. Apollo Alarmsense 2...,Fire Product,6.0,17.28,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
21,21,180852,2011-03-01,141692,1,PIC8/M3/E/BR ORB,INACTIVE 8W M3 S/Sided Pico Low Profile E/Box ...,Pico,1.0,42.00,S1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
22,22,180852,2011-03-01,141692,2,L19EB,Legend L19 For E/B 379 X 186 X 2mm Opal Poly...,Accessories,1.0,0.00,S1412,Impact (ACCOUNT CLOSED) Electrical Distributor...,East Midlands,Richard Mulligan,UK Carrier
23,23,180831,2011-03-01,141687,1,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,2.0,17.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
24,24,180831,2011-03-01,141687,3,17-782/WHT,"Metalwork. Semi Recess Flange for Arc, Powder ...",Accessories,2.0,12.24,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
25,25,180831,2011-03-01,141687,4,27-102,Metalwork.Recessing Frame Fixing Bracket,Accessories,2.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
26,26,180830,2011-03-01,141662,1,kn16/m3 orb,16W 2D M3 Kandel White Opal Diff,Kandel,1.0,49.22,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
27,27,180830,2011-03-01,141662,3,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S1617,Eyre & Elliston Limited,East Midlands,NaN,UK Carrier
28,28,180835,2011-03-01,141664,1,fpa-235,S65 Detectors Base with Diode. Apollo Series ...,Fire Product,7.0,12.53,S2191,LH Electrical Limited,East Midlands,Liam Hassell,UK Carrier
29,29,180839,2011-03-01,141671,2,ar8/m3 orb,Arc 8W HF M3,Arc,6.0,144.96,S751,ABCO Electrical Distributors Limited,South West,Mike Merrit,UK Carrier
30,30,180829,2011-03-01,141676,1,FPA-122,INACTIVE Smoke Detector Test Aerosol (250ml),Fire Product,5.0,32.20,S1551,Edmundson Electrical (400),North West,NaN,UK Carrier
31,31,180838,2011-03-01,141682,1,ODS20/NM3/TH ORB,New Style Odet 2x20W Tungsten Halogen NM3 Grey...,Odet,2.0,105.56,S654,Rexel UK Limited,West Midlands (East),NaN,UK Carrier
32,32,180831,2011-03-01,141687,2,ED8/M3/E ORB,8 Watt Economy M3 Eden with White Base & Fresn...,Eden,2.0,22.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
33,33,180831,2011-03-01,141687,5,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
34,34,180831,2011-03-01,141687,6,FPA-235,S65 Detectors Base with Diode. Apollo Series ...,Fire Product,1.0,0.00,S1730,Regent Electrical Distributors,South Coast,Graham Allen,UK Carrier
35,35,180849,2011-03-01,141689,2,FPA-240,Alarmsense Heat Comb. Apollo Alarmsense 2-Wir...,Fire Product,1.0,21.57,S75,NEW Electrical Distributors Limited,West Midlands (East),Steve Liddell,UK Carrier
36,36,180863,2011-03-01,141704,1,MZ28/M3 ORB,28W 2D Maintained Mezzina White Pr Diff,Mezzina,6.0,304.02,S1480,Edmundson Electrical (110),West Midlands (East),NaN,UK Carrier
37,37,180859,2011-03-01,141705,2,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,Accessories,3.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
38,38,180858,2011-03-01,141703,1,FP-018,Use FP-313 Conventional Panel with 4 Zones fo...,Fire Product,1.0,137.93,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
39,39,180858,2011-03-01,141703,3,FPA-1010,Twin Flex & Multipoint,Fire Product,14.0,260.40,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
40,40,180858,2011-03-01,141703,4,FPA-1011,Twin Flex Call Point,Fire Product,4.0,40.80,S1542,Edmundson Electrical (275),East Midlands,Nigel Bache,UK Carrier
41,41,180863,2011-03-01,141704,2,ML4003P3 ORB,M3 Low Profile Module 3x4Ah + DDP For 16W 2D-3...,ML-Range,10.0,198.10,S1480,Edmundson Electrical (110),West Midlands (East),NaN,UK Carrier
42,42,180859,2011-03-01,141705,1,SAV8/NM3/WH/A ORB,8W NM3 Savona Edge Lit E/Sign Head White Size A,Savona,5.0,309.65,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
43,43,180859,2011-03-01,141705,3,L16EL-A,Legend Printed L16 S/Sided Suitable For All Ed...,Accessories,1.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
44,44,180859,2011-03-01,141705,4,L20EL-A,Legend Printed L20 S/Sided Suitable For All Ed...,Accessories,1.0,0.00,S1563,Edmundson Electrical,South Coast,NaN,UK Carrier
45,45,180857,2011-03-01,141397,1,ods21/nm3/tm14 orb,New Style Odet 2x21W Tungsten NM3 Grey Inc 14 ...,Odet,4.0,282.04,S236,Rexel UK - AP Department (M3),East Midlands,NaN,UK Carrier
46,46,180856,2011-03-01,141699,1,ED8/NM3/E ORB,8 Watt Economy NM3 Eden with White Base & Fres...,Eden,6.0,54.00,S1521,Eyre & Elliston Limited,West Midlands (East),NaN,UK Carrier
47,47,180833,2011-03-01,141661,1,b165/315 orb,3x1.5Ah Nickel Cadmium In Line Battery with En...,Batteries,2.0,14.88,S1846,Herts Electrical Wholesale Limited,East Anglia,Stuart Beevor,UK Carrier
48,48,180825,2011-03-01,141665,1,16-618,Battery 3x1.5Ah Stick Sleeved & Tagged with Re...,Battery Component,1.0,5.06,s1212,ADI Gardiner Limited,North West,NaN,UK Carrier
49,49,180840,2011-03-01,141685,1,28-489,Self Adhesive European Directive Stickers (Sma...,Accessories,12.0,18.96,S816,GCG Electrical Wholesalers (Edmundson 584),West Midlands (West),Barry Guest,Customer Collection

## Fix Missing INV_ProdFam Values

See if we can fill in the missing values in INV_ProdFam column based on the IMA_ItemID column
Any we cannot fill we will delete

In [36]:
#find how many INV_ProdFam values are missing
dfTemp = dfSales_DataSet_Work[dfSales_DataSet_Work["INV_ProdFam"].isnull()]
#show results
dfTemp.head(100)

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
1285,1285,181548,2011-03-16,Misc Inv,2,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,NaN,2.0,0.00,S1534,Edmundson Electrical,Scotland,NaN,UK Carrier
1387,1387,181546,2011-03-16,Misc Inv,3,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,NaN,1.0,0.00,S639,City Electrical Factors (Glasgow South Group),Scotland,Robert Shields,UK Carrier
1388,1388,181555,2011-03-16,Misc Inv,1,PIC8/M3/E,INACTIVE Pico Maintained 8W Economy Version (S...,NaN,2.0,66.40,S1955,Holland House Electrical Ltd,Scotland,NaN,Amtrak
1389,1389,181545,2011-03-16,Misc Inv,2,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,NaN,1.0,0.00,S639,City Electrical Factors (Glasgow South Group),Scotland,Robert Shields,UK Carrier
1390,1390,181547,2011-03-16,Misc Inv,2,L19EL-A,Legend Printed L19 S/Sided Suitable For All Ed...,NaN,4.0,0.00,S639,City Electrical Factors (Glasgow South Group),Scotland,Robert Shields,UK Carrier
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16949,16949,189968,2011-09-08,Misc Inv,2,L19EB,Legend L19 For E/B 379 X 186 X 2mm Opal Poly...,NaN,1.0,0.00,S1027,Allied Electrical Wholesale Limited,Scotland,Patrick Reilly,UK Carrier
17134,17134,190085,2011-09-12,Misc Inv,5,FP-019,Use FP-314 Conventional Panel with 8 Zones f...,NaN,1.0,269.00,S1579,Sabel Bennett & Fountain (Edmundson 520),West Midlands (East),NaN,UK Carrier
17135,17135,190085,2011-09-12,Misc Inv,4,FP-018,Use FP-313 Conventional Panel with 4 Zones fo...,NaN,1.0,160.00,S1579,Sabel Bennett & Fountain (Edmundson 520),West Midlands (East),NaN,UK Carrier
17136,17136,190085,2011-09-12,Misc Inv,3,FPA-008,Red Electronic sounder103 dBA @ 1Mtr 12mA,NaN,7.0,70.00,S1579,Sabel Bennett & Fountain (Edmundson 520),West Midlands (East),NaN,UK Carrier
17137,17137,190085,2011-09-12,Misc Inv,6,FPA-1009,Twin Flex Multipoint & Sounder,NaN,5.0,114.85,S1579,Sabel Bennett & Fountain (Edmundson 520),West Midlands (East),NaN,UK Carrier

In [37]:
#now update INV_ProdFam based on its related column: INV_ItemID
modETL.funcUpdateRelatedRecords(dfSales_DataSet_Work, "INV_ItemID", "INV_ProdFam")
#show results
dfSales_DataSet_Work.head(100)

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
0,0,180851,2011-03-01,140079,3,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
1,1,180851,2011-03-01,140079,4,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
2,2,180851,2011-03-01,140079,2,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
3,3,180834,2011-03-01,141347,1,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
4,4,180834,2011-03-01,141347,2,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,180889,2011-03-02,141716,3,FPA-547,Mains Voltage Safety Isolator Switch,Fire Product,1.0,21.19,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
96,96,180889,2011-03-02,141716,6,FPA-266,XP95 Optical Smoke Detector. Apollo XP95 Dev...,Fire Product,17.0,365.36,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
97,97,180889,2011-03-02,141716,9,FPA-277,XP95 24V Input/Output Unit with Isolator & Bac...,Fire Product,2.0,84.01,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
98,98,180889,2011-03-02,141716,10,FPA-263,XP95 55°C Heat Detector. Apollo XP95 Devices,Fire Product,2.0,42.98,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
99,99,180883,2011-03-02,141563,2,BE8/NM3 ORB,8W NM3 Bewdley White Body Clear Freznal Diff,Bewdley,16.0,496.00,S1104,Riverbank Electrical Wholesale Limited,Scotland,Barry Inglis,UK Carrier

## Observations - Fix Missing INV_ProdFam Values

Function worked! INV_ProdFam has no missing values

## Fix Missing INV_TerritoryCodes Values

See if we can fill in the missing values in INV_TerritoryCodes column based on the IMA_CustomerID column
Any we cannot fill we will delete

In [38]:
#now update INV_TerritoryCodes based on its related column: INV_CustomerID
modETL.funcUpdateRelatedRecords(dfSales_DataSet_Work, "INV_CustomerID", "INV_TerritoryCodes")
#show results
dfSales_DataSet_Work.head(100)

,Unnamed: 0,INV_InvoiceID,INV_InvoiceDate,INV_SalesOrderID,INV_SOLineNbr,INV_ItemID,IMA_ItemName,INV_ProdFam,INV_InvoiceQty,INV_InvoiceAmt,INV_CustomerID,CUS_BillName,INV_TerritoryCodes,CUS_BillContactName,CUS_ShipMethod
0,0,180851,2011-03-01,140079,3,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
1,1,180851,2011-03-01,140079,4,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
2,2,180851,2011-03-01,140079,2,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,Edmundson Electrical Ltd,South West,NaN,UK Carrier
3,3,180834,2011-03-01,141347,1,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
4,4,180834,2011-03-01,141347,2,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,Western (ACCOUNT CLOSED) Electrical Limited,South West,NaN,Despatch Next Day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,180889,2011-03-02,141716,3,FPA-547,Mains Voltage Safety Isolator Switch,Fire Product,1.0,21.19,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
96,96,180889,2011-03-02,141716,6,FPA-266,XP95 Optical Smoke Detector. Apollo XP95 Dev...,Fire Product,17.0,365.36,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
97,97,180889,2011-03-02,141716,9,FPA-277,XP95 24V Input/Output Unit with Isolator & Bac...,Fire Product,2.0,84.01,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
98,98,180889,2011-03-02,141716,10,FPA-263,XP95 55°C Heat Detector. Apollo XP95 Devices,Fire Product,2.0,42.98,S1539,Edmundson-Harding (268),West Midlands (East),NaN,UK Carrier
99,99,180883,2011-03-02,141563,2,BE8/NM3 ORB,8W NM3 Bewdley White Body Clear Freznal Diff,Bewdley,16.0,496.00,S1104,Riverbank Electrical Wholesale Limited,Scotland,Barry Inglis,UK Carrier

### Observations - Fix Missing INV_TerritoryCodes Values

Function worked! INV_TerritoryCodes has no missing values

## Remove Unnecessary Columns

Will remove:
- Unnamed column as it is an index column
- INV_SalesOrderID as it is not required for analysis
- INV_SOLineNbr as it is not required for analysis
- CUS_BillName as it is not required for analysis also might contravien GDPR as it contains a business name
  and this data will be on a public server so will remove it to be safe
- CUS_BillContactlName as it is not required for analysis also might contravien GDPR as it contains a business name
  and this data will be on a public server so will remove it to be safe

In [39]:
#going to remove:
dfSales_DataSet_Work.drop(columns=["Unnamed: 0","INV_SalesOrderID", "INV_SOLineNbr", "CUS_BillName", 
                                   "CUS_BillContactName"], inplace=True)

#check results
dfSales_DataSet_Work.info()

<class 'pandas.DataFrame'>
RangeIndex: 189151 entries, 0 to 189150
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   INV_InvoiceID       189151 non-null  str
 1   INV_InvoiceDate     189151 non-null  datetime64[us]
 2   INV_ItemID          189151 non-null  str
 3   IMA_ItemName        189151 non-null  str
 4   INV_ProdFam         189151 non-null  str
 5   INV_InvoiceQty      189151 non-null  float64
 6   INV_InvoiceAmt      189151 non-null  float64
 7   INV_CustomerID      189151 non-null  str
 8   INV_TerritoryCodes  189151 non-null  str
 9   CUS_ShipMethod      189151 non-null  str
dtypes: datetime64[us](1), float64(2), str(7)
memory usage: 33.2 MB

## Rename Columns

Will rename *all* columns being used

In [40]:
#rename rest of the columns

dfSales_DataSet_Work.rename(columns={
    "INV_ItemID": "ItemID", 
    "INV_ProdFam": "ProductFamily",
    "IMA_ItemName": "ItemName",
    "INV_ItemID": "ItemID",
    "INV_InvoiceID": "InvoiceID",
    "INV_InvoiceDate": "InvoiceDate",
    "INV_InvoiceQty": "InvoiceQty",
    "INV_InvoiceAmt": "InvoiceAmt",
    "INV_CustomerID": "CustomerID",
    "INV_TerritoryCodes": "TerritoryCodes",
    "CUS_BillContactName": "ContactName",
    "CUS_ShipMethod": "ShipMethod",
    "CUS_BillName": "CustomerName"
    }, inplace=True)

#show results
dfSales_DataSet_Work.info()

<class 'pandas.DataFrame'>
RangeIndex: 189151 entries, 0 to 189150
Data columns (total 10 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceID       189151 non-null  str
 1   InvoiceDate     189151 non-null  datetime64[us]
 2   ItemID          189151 non-null  str
 3   ItemName        189151 non-null  str
 4   ProductFamily   189151 non-null  str
 5   InvoiceQty      189151 non-null  float64
 6   InvoiceAmt      189151 non-null  float64
 7   CustomerID      189151 non-null  str
 8   TerritoryCodes  189151 non-null  str
 9   ShipMethod      189151 non-null  str
dtypes: datetime64[us](1), float64(2), str(7)
memory usage: 33.2 MB

## Observations - Sales_Features_DataSet

Columns confirmed removed:

INV_SalesOrderID, INV_SOLineNbr

All other columns renamed

## Feature Engineering

Need to add columns:
- day
- month
- year
- quarter

In [41]:
#add day, month and year columns and a yearmonth column
dfSales_DataSet_Work["Day"] = dfSales_DataSet_Work["InvoiceDate"].dt.day
dfSales_DataSet_Work["Month"] = dfSales_DataSet_Work["InvoiceDate"].dt.month    
dfSales_DataSet_Work["Year"] = dfSales_DataSet_Work["InvoiceDate"].dt.year
dfSales_DataSet_Work["Quarter"] = dfSales_DataSet_Work["InvoiceDate"].dt.quarter
dfSales_DataSet_Work["YearMonth"] = (dfSales_DataSet_Work["InvoiceDate"].dt.year.astype(str) + 
                                     dfSales_DataSet_Work["InvoiceDate"].dt.month.astype(str))
#convert to int
dfSales_DataSet_Work["YearMonth"] =dfSales_DataSet_Work["YearMonth"].astype(int)

#show results
dfSales_DataSet_Work.head(5000)

,InvoiceID,InvoiceDate,ItemID,ItemName,ProductFamily,InvoiceQty,InvoiceAmt,CustomerID,TerritoryCodes,ShipMethod,Day,Month,Year,Quarter,YearMonth
0,180851,2011-03-01,17-972,Metalwork-Galvanised Retaining Brackets For Ca...,Luminaire Component,2.0,0.00,S2128,South West,UK Carrier,1,3,2011,1,20113
1,180851,2011-03-01,17-625,M4 x 40mm Steel Pozi Pan Head M/Screw BZP Plated,Luminaire Component,2.0,0.00,S2128,South West,UK Carrier,1,3,2011,1,20113
2,180851,2011-03-01,17-795/WHT,Metalwork White Recessing Frame Bewdley,Accessories,1.0,6.21,S2128,South West,UK Carrier,1,3,2011,1,20113
3,180834,2011-03-01,SAV8/24/D/A ORB,8W 24V Ac/Dc Savona Edge Lit E/Sign Head Brass...,Savona,1.0,76.14,S2061,South West,Despatch Next Day,1,3,2011,1,20113
4,180834,2011-03-01,l1919el-a,Legend Printed L19 Both Sides Suitable For All...,Luminaire Component,1.0,0.00,S2061,South West,Despatch Next Day,1,3,2011,1,20113
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,183671,2011-04-28,FPA-127,220V Mains Heat Detector Tester,Fire Product,1.0,170.60,S1983,South Coast,UK Carrier,28,4,2011,2,20114
4996,183791,2011-04-28,16-502,Battery Lead Acid 6V 12Ah,Battery Component,60.0,0.00,121,Non EU,Export,28,4,2011,2,20114
4997,184100,2011-04-28,SAV8/NM3/WH/R ORB,8W NM3 Savona Recessed Edge Lit E/Sign Head White,Savona,1.0,40.01,628,Non EU,Export,28,4,2011,2,20114
4998,184100,2011-04-28,L1620EL-A,Legend Printed L16 One Side L20 Other Suitable...,Luminaire Component,1.0,0.00,628,Non EU,Export,28,4,2011,2,20114
4999,184100,2011-04-28,SAV8/NM3/WH/R ORB,8W NM3 Savona Recessed Edge Lit E/Sign Head White,Savona,3.0,115.23,628,Non EU,Export,28,4,2011,2,20114

## Observations - Feature Engineering

## Save Work DataFrame To CSV File

In [42]:
#create new DataFrame for cleaned data
dfCleaned = dfSales_DataSet_Work.copy()

#save the cleaned DataFrame to a new file
modETL.funcSaveDataFrameToCleanedFile(dfCleaned)

Saved: Sales_InvoiceData To Visualisation Folder

# Conclusions and Next Steps

ETL went well, DataSet ready for use